package database

import objects.Color
import objects.Coordinates
import objects.Country
import objects.Person
import objects.Product
import objects.UnitOfMeasure
import java.sql.Connection
import java.sql.DriverManager
import java.sql.Types

/**
 * Manages the single PostgreSQL connection and all SQL operations.
 * Every public method is synchronized on [this] to guarantee thread-safe access
 * from the multithreaded request handlers.
 *
 * The schema is created on first run via [initSchema].
 * Product IDs are generated by the database sequence [products_id_seq].
 *
 * @constructor Opens a JDBC connection to [url] with [user] and [password].
 */
class DatabaseManager(url: String, user: String, password: String) {

    private val connection: Connection = DriverManager.getConnection(url, user, password)

    /**
     * Creates the users table, the products table, and the id sequence
     * if they do not already exist.
     */
    @Synchronized
    fun initSchema() {
        connection.createStatement().use { stmt ->
            stmt.execute("CREATE SEQUENCE IF NOT EXISTS products_id_seq")
            stmt.execute(
                """
                CREATE TABLE IF NOT EXISTS users (
                    login         VARCHAR(255) PRIMARY KEY,
                    password_hash VARCHAR(255) NOT NULL
                )
                """.trimIndent()
            )
            stmt.execute(
                """
                CREATE TABLE IF NOT EXISTS products (
                    id                BIGINT           PRIMARY KEY DEFAULT nextval('products_id_seq'),
                    collection_key    VARCHAR(255)     NOT NULL,
                    name              VARCHAR(255)     NOT NULL,
                    coord_x           BIGINT           NOT NULL,
                    coord_y           DOUBLE PRECISION NOT NULL,
                    creation_date     VARCHAR(255)     NOT NULL,
                    price             BIGINT           NOT NULL,
                    part_number       VARCHAR(255),
                    manufacture_cost  BIGINT,
                    unit_of_measure   VARCHAR(50),
                    owner_name        VARCHAR(255)     NOT NULL,
                    owner_height      BIGINT           NOT NULL,
                    owner_hair_color  VARCHAR(50)      NOT NULL,
                    owner_nationality VARCHAR(50),
                    creator_login     VARCHAR(255)     NOT NULL REFERENCES users(login)
                )
                """.trimIndent()
            )
        }
    }

    /**
     * Returns the stored MD2 password hash for [login], or null if the user does not exist.
     *
     * @param login the user's login to look up
     * @return the stored hash string, or null
     */
    @Synchronized
    fun findUser(login: String): String? {
        connection.prepareStatement(
            "SELECT password_hash FROM users WHERE login = ?"
        ).use { ps ->
            ps.setString(1, login)
            ps.executeQuery().use { rs ->
                return if (rs.next()) rs.getString("password_hash") else null
            }
        }
    }

    /**
     * Inserts a new user record with the given [login] and pre-hashed [passwordHash].
     *
     * @param login the new user's login
     * @param passwordHash the MD2 hex hash of the user's password
     */
    @Synchronized
    fun createUser(login: String, passwordHash: String) {
        connection.prepareStatement(
            "INSERT INTO users (login, password_hash) VALUES (?, ?)"
        ).use { ps ->
            ps.setString(1, login)
            ps.setString(2, passwordHash)
            ps.executeUpdate()
        }
    }

    /**
     * Loads all products and their creator logins from the database.
     *
     * @return a pair of (products map keyed by collection_key, creatorLogins map keyed by product id)
     */
    @Synchronized
    fun loadProducts(): Pair<Map<String, Product>, Map<Long, String>> {
        val products = LinkedHashMap<String, Product>()
        val creators = HashMap<Long, String>()
        connection.createStatement().use { stmt ->
            stmt.executeQuery("SELECT * FROM products").use { rs ->
                while (rs.next()) {
                    val id = rs.getLong("id")
                    val mcRaw = rs.getLong("manufacture_cost")
                    val mc = if (rs.wasNull()) null else mcRaw
                    val uom = rs.getString("unit_of_measure")?.let { UnitOfMeasure.valueOf(it) }
                    val nat = rs.getString("owner_nationality")?.let { Country.valueOf(it) }
                    val product = Product(
                        id = id,
                        name = rs.getString("name"),
                        coordinates = Coordinates(
                            x = rs.getLong("coord_x"),
                            y = rs.getDouble("coord_y")
                        ),
                        creationDate = rs.getString("creation_date"),
                        price = rs.getLong("price"),
                        partNumber = rs.getString("part_number"),
                        manufactureCost = mc,
                        unitOfMeasure = uom,
                        owner = Person(
                            name = rs.getString("owner_name"),
                            height = rs.getLong("owner_height"),
                            hairColor = Color.valueOf(rs.getString("owner_hair_color")),
                            nationality = nat
                        )
                    )
                    products[rs.getString("collection_key")] = product
                    creators[id] = rs.getString("creator_login")
                }
            }
        }
        return products to creators
    }

    /**
     * Deletes all products with the given [key] unconditionally.
     * Used internally when a user replaces their own product at an existing key.
     *
     * @param key the collection key whose product should be deleted
     */
    @Synchronized
    fun deleteByKey(key: String) {
        connection.prepareStatement(
            "DELETE FROM products WHERE collection_key = ?"
        ).use { ps ->
            ps.setString(1, key)
            ps.executeUpdate()
        }
    }

    /**
     * Inserts [product] under [key] for [creatorLogin] and returns the id assigned by the sequence.
     *
     * @param key the collection key
     * @param product the product to insert (its id field is ignored; the sequence assigns one)
     * @param creatorLogin the login of the user inserting the product
     * @return the database-generated id
     */
    @Synchronized
    fun insertProduct(key: String, product: Product, creatorLogin: String): Long {
        connection.prepareStatement(
            """
            INSERT INTO products (collection_key, name, coord_x, coord_y, creation_date, price,
                part_number, manufacture_cost, unit_of_measure,
                owner_name, owner_height, owner_hair_color, owner_nationality, creator_login)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            RETURNING id
            """.trimIndent()
        ).use { ps ->
            ps.setString(1, key)
            ps.setString(2, product.name)
            ps.setLong(3, product.coordinates.x)
            ps.setDouble(4, product.coordinates.y)
            ps.setString(5, product.creationDate)
            ps.setLong(6, product.price)
            ps.setString(7, product.partNumber)
            if (product.manufactureCost != null) ps.setLong(8, product.manufactureCost as Long)
            else ps.setNull(8, Types.BIGINT)
            ps.setString(9, product.unitOfMeasure?.name)
            ps.setString(10, product.owner.name)
            ps.setLong(11, product.owner.height)
            ps.setString(12, product.owner.hairColor.name)
            ps.setString(13, product.owner.nationality?.name)
            ps.setString(14, creatorLogin)
            ps.executeQuery().use { rs ->
                rs.next()
                return rs.getLong("id")
            }
        }
    }

    /**
     * Updates all mutable fields of the product with [id], restricted to rows owned by [creatorLogin].
     * The id, collection_key, creation_date, and creator_login columns are never modified.
     *
     * @param id the id of the product to update
     * @param product new field values
     * @param creatorLogin ownership guard; the UPDATE is a no-op if the row belongs to someone else
     * @return true if a row was updated
     */
    @Synchronized
    fun updateProduct(id: Long, product: Product, creatorLogin: String): Boolean {
        connection.prepareStatement(
            """
            UPDATE products SET
                name = ?, coord_x = ?, coord_y = ?, price = ?,
                part_number = ?, manufacture_cost = ?, unit_of_measure = ?,
                owner_name = ?, owner_height = ?, owner_hair_color = ?, owner_nationality = ?
            WHERE id = ? AND creator_login = ?
            """.trimIndent()
        ).use { ps ->
            ps.setString(1, product.name)
            ps.setLong(2, product.coordinates.x)
            ps.setDouble(3, product.coordinates.y)
            ps.setLong(4, product.price)
            ps.setString(5, product.partNumber)
            if (product.manufactureCost != null) ps.setLong(6, product.manufactureCost as Long)
            else ps.setNull(6, Types.BIGINT)
            ps.setString(7, product.unitOfMeasure?.name)
            ps.setString(8, product.owner.name)
            ps.setLong(9, product.owner.height)
            ps.setString(10, product.owner.hairColor.name)
            ps.setString(11, product.owner.nationality?.name)
            ps.setLong(12, id)
            ps.setString(13, creatorLogin)
            return ps.executeUpdate() > 0
        }
    }

    /**
     * Deletes the product with [id] owned by [creatorLogin].
     *
     * @param id the id of the product to delete
     * @param creatorLogin ownership guard
     * @return true if a row was deleted
     */
    @Synchronized
    fun deleteProduct(id: Long, creatorLogin: String): Boolean {
        connection.prepareStatement(
            "DELETE FROM products WHERE id = ? AND creator_login = ?"
        ).use { ps ->
            ps.setLong(1, id)
            ps.setString(2, creatorLogin)
            return ps.executeUpdate() > 0
        }
    }

    /**
     * Deletes all products owned by [creatorLogin].
     *
     * @param creatorLogin the login whose products should be deleted
     * @return the number of deleted rows
     */
    @Synchronized
    fun deleteAllByCreator(creatorLogin: String): Int {
        connection.prepareStatement(
            "DELETE FROM products WHERE creator_login = ?"
        ).use { ps ->
            ps.setString(1, creatorLogin)
            return ps.executeUpdate()
        }
    }

    /**
     * Deletes all products owned by [creatorLogin] whose price is strictly less than [price].
     *
     * @param price the exclusive upper price bound
     * @param creatorLogin ownership filter
     * @return the number of deleted rows
     */
    @Synchronized
    fun deleteLowerByCreator(price: Long, creatorLogin: String): Int {
        connection.prepareStatement(
            "DELETE FROM products WHERE price < ? AND creator_login = ?"
        ).use { ps ->
            ps.setLong(1, price)
            ps.setString(2, creatorLogin)
            return ps.executeUpdate()
        }
    }

    /**
     * Deletes all products owned by [creatorLogin] whose collection_key is lexicographically
     * greater than [key].
     *
     * @param key the exclusive lower key bound
     * @param creatorLogin ownership filter
     * @return the number of deleted rows
     */
    @Synchronized
    fun deleteGreaterKeyByCreator(key: String, creatorLogin: String): Int {
        connection.prepareStatement(
            "DELETE FROM products WHERE collection_key > ? AND creator_login = ?"
        ).use { ps ->
            ps.setString(1, key)
            ps.setString(2, creatorLogin)
            return ps.executeUpdate()
        }
    }
}