package src.productcreation;

import src.baseabstractions.AutoGeneratedId;

import java.util.TreeSet;

public class LongIdManager<T extends AutoGeneratedId<Long>> {
    private static TreeSet<Long> ids = new TreeSet<>();

    public Long generateId() {
        Long maxId = ids.last();
        return maxId + 1;
    }

    public boolean addId(T product) {
        return ids.add(product.getId());
    }

    public boolean removeId(T product) {
        return ids.remove(product.getId());
    }

    public TreeSet<Long> getIds() {
        return ids;
    }

    public boolean isIdExists(T product) {
        return ids.contains(product.getId());
    }

    public boolean isIdExists(Long id) {
        return ids.contains(id);
    }
}
