package src.productcreation;

import src.baseabstractions.AutoGeneratedId;

import java.util.TreeSet;

/**
 * Manager class for handling Long-type auto-generated IDs.
 * Maintains a set of existing IDs and provides ID generation and validation.
 *
 * @param <T> the type of object that has an auto-generated Long ID, must
 *            implement AutoGeneratedId<Long>
 */
public class LongIdManager<T extends AutoGeneratedId<Long>> {
    private static TreeSet<Long> ids = new TreeSet<>();

    /**
     * Generates a new unique ID.
     * The new ID is one greater than the maximum existing ID, or 1 if no IDs exist.
     *
     * @return a new unique Long ID
     */
    public Long generateId() {
        Long maxId = ids.size() > 0 ? ids.last() : 0;
        return maxId + 1;
    }

    /**
     * Adds the ID from the specified product to the set of managed IDs.
     *
     * @param product the product whose ID should be added
     * @return true if the ID was successfully added, false if it already exists
     */
    public boolean addId(T product) {
        return ids.add(product.getId());
    }

    /**
     * Removes the ID from the specified product from the set of managed IDs.
     *
     * @param product the product whose ID should be removed
     * @return true if the ID was successfully removed, false if it didn't exist
     */
    public boolean removeId(T product) {
        return ids.remove(product.getId());
    }

    /**
     * Removes the specified ID from the set of managed IDs.
     *
     * @param id the ID to be removed
     * @return true if the ID was successfully removed, false if it didn't exist
     */
    public boolean removeId(Long id) {
        return ids.remove(id);
    }

    /**
     * Clears all managed IDs.
     */
    public void clear() {
        ids = new TreeSet<>();
    }

    /**
     * Returns the set of all managed IDs.
     *
     * @return TreeSet containing all current IDs
     */
    public TreeSet<Long> getIds() {
        return ids;
    }

    /**
     * Checks if the ID from the specified product exists in the managed set.
     *
     * @param product the product whose ID to check
     * @return true if the ID exists, false otherwise
     */
    public boolean isIdExists(T product) {
        return ids.contains(product.getId());
    }

    /**
     * Checks if the specified ID exists in the managed set.
     *
     * @param id the ID to check
     * @return true if the ID exists, false otherwise
     */
    public boolean isIdExists(Long id) {
        return ids.contains(id);
    }
}