package src.baseabstractions;

/**
 * Interface for objects that have an automatically generated identifier.
 *
 * @param <T> the type of the identifier (e.g., Integer, Long, String)
 */
public interface AutoGeneratedId<T> {
    /**
     * Returns the automatically generated identifier.
     *
     * @return the identifier value of type T
     */
    T getId();
}